### PR TITLE
Update of references links of security risks

### PR DESCRIPTION
**Pull request by paulagmf**
It was missing the .md extensions of the files.

### CODE REVIEW

**Comment by ChristopherHackett** [comment]
This will break navigation on the rendered website https://owasp.org/www-project-top-10-ci-cd-security-risks/ (which presumably is the target output). 

Also just noticed project should have a readme file to point to the target site like other OWASP repos.

**Comment by paulagmf** [comment]
Ok. I proposed because the readme from github it is broken because of the missing extension if you access the index.md page.

https://github.com/OWASP/www-project-top-10-ci-cd-security-risks/blob/main/index.md

But I understand that is better to break the index.md than the web site of the project itself ;)

**Comment by ChristopherHackett** [comment]
Maybe we can fix it with redirects?

**Comment by paulagmf** [comment]
Yeah, sure.

**Comment by ChristopherHackett** [comment]
I had a look at setting up redirects and played with it locally. 

The plug-in used was [jekyll-redirect-from](https://github.com/jekyll/jekyll-redirect-from) as allowed in Github Pages. This causes client side redirect (javascript) pages to be added ... however in the case of MD resources it caused a file download instead of redirect! It might be a bit of trail and error to get this working correctly. 

Alternatively does @OWASPFoundation have a guide on using their content system?

**Comment by kingthorin** [comment]
Edit: Following the inquiry on [OWASP Slack](https://owasp.slack.com/archives/C04T40NND/p1671201731695549), I [tested the following locally](https://owasp.org/migration/#setup-a-local-testing-environment).

The following config setting will resolve the issue of having `.md` for GitHub but bare links for the web deployed version:
```diff
diff --git a/_config.yml b/_config.yml
index 9ca7a3e..c4073b8 100644
--- a/_config.yml
+++ b/_config.yml
@@ -1,3 +1,4 @@
 remote_theme: "owasp/www--site-theme@main"
+permalink: :path
 plugins:
- - jekyll-include-cache-0.2.0
\ No newline at end of file
+ - jekyll-include-cache-0.2.0
```

I'd also suggest the following changes to make your info bar a little more modern and conform with [Project Committee](https://owasp.org/www-committee-project/) guidance.

```diff
diff --git a/info.md b/info.md
index 3b5e5b3..9f82e99 100644
--- a/info.md
+++ b/info.md
@@ -1,10 +1,17 @@
 ### Top 10 CI-CD Security Risks Information
-[![Incubator Project][inc-proj-logo]{:height="66px"}][inc-proj]
-![Documentation Project][doc-proj-logo]
 
-[![Builders][builders-logo]][builders]
-[![Breakers][breakers-logo]][breakers]
-[![Defenders][defenders-logo]][defenders]
+* <i class="fas fa-egg" style="font-size: 1.3em; color:#53AAE5;"></i>
+  <span style="font-size: 1.3em;">Incubator Project</span>
+
+#### Classification
+
+* <i class="fas fa-file-alt" style="color:#233e81;"></i> Documentation
+
+#### Audience
+
+* <i class="fas fa-toolbox" style="color:#233e81;"></i> Builder
+* <i class="fas fa-hammer" style="color:#233e81;"></i> Breaker
+* <i class="fas fa-shield-alt" style="color:#233e81;"></i> Defender
 
 ### Downloads or Social Links
 * [Download](https://github.com/OWASP/www-project-top-10-ci-cd-security-risks/raw/3204d6d181e2a5517ffdcbe208fb536b9cc6c50b/assets/OWASP_Top_10_CICD_Risks.pdf)
```

image

**Comment by kingthorin** [comment]
The conflicts are only going to get worse with time. Do you need further help making this happen?

**Comment by omer-cider** [comment]
Thanks everyone for your contribution & assistance! I pushed the changes suggested by @kingthorin.

**Review by omer-cider — APPROVED** [review]

**Comment by kingthorin** [comment]
Happy to help. Feel free to hit me up on slack if you get stuck again.

**Pull request merged**
